<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <?php echo $this->getContent() ?>
    
    <?php echo $this->flash->output() ?>
</body>
</html>
