<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="../css/index.css">
    <title>Bustronome</title>
</head>

<body>
<div class="sidebar-container">
  <div class="sidebar-logo">
  </div>
  <ul class="sidebar-navigation">
    <li class="header"><img src="https://www.bustronome.com//wp-content/uploads/2014/06/logo2.png" alt="logo"></li>
    <li>
      <a href="..\..\views\makeabooking\index.phtml">
        <i class="fa fa-info-circle" aria-hidden="true"></i> MAKE A BOOKING
      </a>
    </li>
    <li>
      <a href="#">
        <i class="fa fa-info-circle" aria-hidden="true"></i>☆ GIFT CARD ☆
      </a>
    </li>
    
    <li>
      <a href="#">
        <i class="fa fa-info-circle" aria-hidden="true"></i> OUR OFFERS
      </a>
    </li>
    <li>
      <a href="#">
        <i class="fa fa-info-circle" aria-hidden="true"></i> CONCEPT
      </a>
    </li>
    <li>
      <a href="#">
        <i class="fa fa-info-circle" aria-hidden="true"></i> PRIVATIZATION
      </a>
    </li>
    <li>
      <a href="#">
        <i class="fa fa-info-circle" aria-hidden="true"></i> NEWS
      </a>
    </li>
    <li>
      <a href="#">
        <i class="fa fa-info-circle" aria-hidden="true"></i> VIDEO & GALLERY
      </a>
    </li>
    <li>
      <a href="#">
        <i class="fa fa-info-circle" aria-hidden="true"></i> FAQ
      </a>
    </li>
    <li>
      <a href="#">
        <i class="fa fa-info-circle" aria-hidden="true"></i> CONTACT US
      </a>
    </li>
  </ul>
    <div class="links-place">
      <img src="..\..\img\2831421_drop pin_google maps_location_map_map icon_icon (1).png" class="icon">
      ARC DE TRIOMPHE</span><br>
      <a id="liun" href="https://www.google.com/maps/place/Bustronome+-+Paris/@48.872752,2.294031,15z/data=!4m5!3m4!1s0x0:0x2b80095c2d0654ca!8m2!3d48.872752!4d2.294031 " target="_blank">corner with Kleber avenue</a>
        </div>
      </div>
<div  class="carou">
  <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="..\..\img\Bustronome-91.jpg" class="d-block w-30 h-30" alt="...">
        </div>
        <div class="carousel-item">
          <img src="..\..\img\Bustronome-HD-41.jpg" class="d-block w-30" alt="...">
        </div>
        <div class="carousel-item">
          <img src="..\..\img\Bustronome-HD-691.jpg" class="d-block w-30" alt="...">
        </div>
        <div class="carousel-item">
          <img src="..\..\img\Tartare-de-bar-aux-jeunes-pousses-crème-légère-au-citron-vert-thé-Matcha.jpg" class="d-block w-80" alt="...">
        </div>
      </div>
      <!-- <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button> -->
</div>


<main>
<div class="container">
<?= $this->getContent(); ?>
</div>    
</main>  


<footer>
<div class="progress" style="height:5px;">
  <div class="progress-bar" role="progressbar" aria-valuenow="25%" aria-valuemin="25%" aria-valuemax="100"></div>

</div>
 <div class="contact">
   <img src="https://www.bustronome.com/wp-content/uploads/2017/04/tel.jpg" class="icon-tel">
  +33 (0) 954 444 555   
  <img src="https://www.bustronome.com/wp-content/uploads/2017/04/mail.jpg" class="icon-mail">
  <a href="mailto:contact@bustronome.com"> contact@bustronome.com</a>
 </div>
  <div class="devlop">
  <span class="d_in-block privacy">© 2017 Bustronome.
     <a href="https://www.bustronome.com/en/paris/legal-notices/">Legal Notices</a>
      .Developed by</span>
  <p>Made with ♥ by CosaVostra.</p>
  </div>

</footer>
</body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</html>
            