<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="\css\index.css">
        <link rel="stylesheet" href="\css\calendar.css">
        <title>Document</title>
    </head>
    <body>
        
        <!-- <?php echo $this->getContent() ?>
        
        <?php echo $this->flash->output() ?>  -->
        
        <h1>SCHEDULE</h1>

        <?php 
        require("..\src\Date\Month.php");

        $day = $month->getStartingDay()->modify('last monday');

            $month = new App\Date\Month($_GET['month'] ?? null, $_GET['year'] ?? null);

        ?>
          <h1><?= $month->toString();?></h1>
          
          <table class="calendar__table calendar__table--<?= $month->getWeeks();?> weeks">
              <?php for ($i = 0; $i < $month->getWeeks(); $i++) ?>
                <tr>
                    <?php foreach($month->days as $day): ?>
                    <td>
                        <?= $day; ?>
                    </td>
                    <?php endforeach; ?>
                </tr>
          </table>

    </div>
</body>
</html>
